loliGothicK/mitama-cpp-result

include/Result.hpp
include/result/result_impl.hpp
test/Result_Test.cpp

Add injector for `Ok<T>` and `Err<T>`.
`Ok<T>` and `Err<T>` are printable with operator << if and only if T is printable.

add: std::ostream operator<< for Ok and Err

---

include/mitama/maybe/maybe.hpp

Replaced `std::nullopt` with `boost::none`. [Fix #14]

Fix `operator>>` of `maybe` for Boost.Optional

---

include/mitama/maybe/maybe.hpp

Replace return type of `unwrap` with `T&`

---

.github/workflows/full-test.yml

This PR adds GitHub Actions; also, you can check the CI result [here](https://github.com/ken-matsui/mitama-cpp-result/pull/1). After merging this PR, any PRs will automatically hook GitHub Actions by enabling [this setting](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/), and this PR should close ken-matsui/mitama-cpp-result#1.

Add GitHub Actions

---

.circleci/config.yml
CMakeLists.txt
test/CMakeLists.txt

This PR includes:
* Improve CMakeLists.txt to be able to install include dirs
* Disable testing by default
* Fix the problem that building `Result_Test.cpp` fails on macOS (resolves #62)
* Some improvements of CMake command usage
```bash
$ mkdir build
$ cmake ..
$ make install
```
```bash
$ mkdir build
$ cmake .. -DBUILD_TESTING=ON
$ make
$ make test
```

Improve CMakeLists.txt

---

include/mitama/result/detail/fwd.hpp

I just added spaces like the above `success_t` to unify coding style.

Unify coding style

---

include/mitama/result/detail/fwd.hpp

I replaced `decltype(nullptr)` with `nullptr_t` because the former makes no sense.

Replace decltype(nullptr) with nullptr_t

---

include/mitama/result/result.hpp

Usage:
```cpp
mitama::result<int, std::string>
func1(int a)
noexcept
{
if ( first check )
return mitama::failure("first check failed"); // early return
if ( second check )
return mitama::failure("second check failed"); // early return
if ( third check )
return mitama::failure("third check failed"); // early return
// function body...
return mitama::success(42);
}
mitama::result<int, std::string>
func2(int a)
noexcept(MITAMA_CPP_RESULT_TRY_MAY_NOT_PANIC)
{
int value = TRY(func1(a));
return mitama::success(value);
}
// ...
int value = TRY(func2(42));
```
Since [MSVC does not implement compound statements](https://stackoverflow.com/q/5291532), the processing of the TRY macro changes between MSVC and others; therefore, there is a `MITAMA_CPP_RESULT_TRY_MAY_NOT_PANIC` macro to detect whether …

Add a TRY macro like the Rust's `?` operator

---

include/mitama/result/result.hpp
test/CMakeLists.txt
test/result_tests.cpp

When passing a function call like the below,
```cpp
MITAMA_TRY(func(42));
```
this will be expanded that will cause double evaluation:
```cpp
({
if (func(42).is_err()) {
using Err = mitama::failure_t<decltype(func(42))::err_type>;
return std::get<Err>(func(42).into_storage());
}
using Ok = mitama::success_t<decltype(func(42))::ok_type>;
std::get<Ok>(func(42).into_storage()).get();
})
```
So, I fixed the MITAMA_TRY macro to expand like this:
```cpp
({
const auto result = func(42);
if (result.is_err()) {
using Err = mitama::failure_t<decltype(result)::err_type>;
return std::get<Err>(result.into_storage());
}
using Ok = mitama::success_t<decltype(result)::ok_type>;
std::get<Ok>(result.into_storage()).get();
})
```

Avoid double evaluation in the MITAMA_TRY macro

---

include/mitama/thiserror/thiserror.hpp

Fix typo in `thiserror.hpp`: `ineline` -> `inline`

---

include/mitama/thiserror/thiserror.hpp

The following closing braces did not correspond to the declaration of namespaces when C++20 is enabled.
1. C++20 is enabled:
https://github.com/LoliGothick/mitama-cpp-result/blob/fddf59f97930cc16a159e8b10b03198ea27d602a/include/mitama/thiserror/thiserror.hpp#L14
2. Lower version than C++20:
https://github.com/LoliGothick/mitama-cpp-result/blob/fddf59f97930cc16a159e8b10b03198ea27d602a/include/mitama/thiserror/thiserror.hpp#L18
https://github.com/LoliGothick/mitama-cpp-result/blob/fddf59f97930cc16a159e8b10b03198ea27d602a/include/mitama/thiserror/thiserror.hpp#L56

Fix an error with an extraneous closing brace

---

include/mitama/thiserror/thiserror.hpp

This PR brings an option to disable `thiserror::v1` when using C++20.
The `v1` is now disabled by default on C++20 because I think most users do not want to use an extra dependency (`Boost.Metaparse`). When we want to keep `v1`, we can enable it by defining `MITAMA_THISERROR_ENABLE_V1` like `#define MITAMA_THISERROR_ENABLE_V1 true`.

Add an option to disable `thiserror::v1`

---

include/mitama/mitamagic/format.hpp

I'd recommend defining a new namespace for them such as `mitama_fmt`.

Avoid redefinition of 'fmt' when both <format> & <fmt> exist

---

.github/workflows/deploy-docs.yml

I think it would be much better to deploy docs when the master branch is updated. (because when deploying docs failed, we have to bump a redundant release)

Deploy docs when pushed to master

---

include/mitama/result/result.hpp

Now, Boost is completely removed from the library (not from the tests).

Replace boost::hana::id

---

include/mitama/boolinators.hpp
include/mitama/maybe/factory/just_nothing.hpp
include/mitama/maybe/maybe.hpp
include/mitama/maybe/range_to_maybe.hpp
include/mitama/result/detail/dangling.hpp
include/mitama/result/detail/result_impl.hpp
include/mitama/result/factory/failure.hpp
include/mitama/result/factory/success.hpp
include/mitama/result/result.hpp
include/mitama/thiserror/thiserror.hpp

`std::variant` is almost `constexpr` and since [P2231R1](<https://wg21.link/P2231R1>) has adopted for C++23, more operations can be marked as `constexpr`.

add constexpr

---

include/mitama/panic.hpp

This can avoid using fmt::runtime

Use format_string for runtime_panic

---

include/mitama/result/result.hpp

Some of the type constraints for the basic_result constructors that take failure_t check constructability and convertibility against T. However, T is unrelated in this context; use E instead.
See also: https://github.com/loliGothicK/mitama-cpp-result/pull/377/files#diff-5f2deecddbd2a0b580bb6983c6f3c6d1ea8c1895294f5a722b0793e6f271270cL332-L358

Fix incorrect type constraints for basic_result constructors

---

docs/docs/result/APIs.md
docs/docs/result/intro.md
include/mitama/boolinators.hpp
include/mitama/result/detail/fwd.hpp
include/mitama/result/result.hpp
test/result_tests.cpp

Leaving types for result out can be confusing.  For instance, it is difficult to read the meaning of result<> without knowing the actual implementation.  This probably comes from because std::monostate is the implementation details, but now that void is allowed, result<void, void> is clearer than result<>.

Remove default template arguments to result

---

include/mitama/result/result.hpp
test/result_tests.cpp

Although implementing an operator bool for this kind of type is normal in the C++ context, this is error-prone.  As Rust does, it is preferable to avoid implicit conversion.

Remove operator bool from basic_result

---

docs/docs/thiserror/thiserror.md
include/mitama/thiserror/thiserror.hpp
test/anyhow_tests.cpp

In the docs, data_store_error inherits derive_error instead of using error to avoid manually defining the error alias template.  In the derive_error implementation, it makes more sense to use protected for the error type as it is not meant to be used only by derived classes. Also, use class, not struct, as this is for inheritance.  On the userside context, data_store_error uses struct rather than class as it's just a container for error types.

Tweak derive_error

---

include/mitama/maybe/factory/just_nothing.hpp
include/mitama/maybe/maybe.hpp
include/mitama/result/detail/result_impl.hpp
test/maybe_tests.cpp

When `maybe<bool>(maybe<U>)` is called, `maybe<U>` will be converted bool via operator bool(), which always results in `maybe<bool>.is_just()`. This is incorrect when `maybe<U>.is_nothing()`.
This patch removes the operator bool() implementation to avoid this unintentional implicit conversion.
See also: #411

Fix incorrect maybe<bool>(maybe<U>) ctor call

---

include/mitama/maybe/maybe.hpp
include/mitama/panic.hpp
include/mitama/result/result.hpp

The current implementation shows the location information of the actual
implementation location instead of its callsite when an internal panic
happens.
This patch fixes this problem by propagating location information from
the callsite all the way down to runtime_panic.

Propagate locations correctly
